### ISSUE TITLE
Fix Text Trig Missing Close Quote

### ISSUE THREAD

**Issue by TheNitesWhoSay** [TheNitesWhoSay/Chkdraft#140]
When missing a close quote in text trigs the program freezes without a compilation error, ensure this doesn't freeze and gives a proper error.

**Comment by Caden-Fletcher** [comment]
I think I have located the issue.

In TextTrigCompiler.cpp on line 37 the cleanText function call is looping endlessly when a quotation mark is missing in the Text Triggers window.

I'll see if I can find a solution, but if I am not successful at least you now know where the issue is occurring.

**Comment by TheNitesWhoSay** [comment]
Thanks for finding that; the fix is in https://github.com/TheNitesWhoSay/Chkdraft/commit/d1e3a0e272b3470719894c3bb8625f97a68c6780 which should make it to master soon.
