### ISSUE TITLE
[Feature] carbot skin/mod graphics

### ISSUE THREAD

**Issue by AleXoundOS** [TheNitesWhoSay/Chkdraft#171]
Cartooned skin/mod looks very different and many modern UMS maps are more suitable with it.

Are there any tips on implementing this in Chkdraft? [Sc:Pcx::load](https://github.com/TheNitesWhoSay/Chkdraft/blob/f9975902607d9cc22867b86a1c5b3e8017e51123/MappingCoreLib/Sc.cpp#L3890C1-L3929C1) seems to load palette data from PCX. But I'm not sure whether it's relevant.
As a reference, here is a function which presumably loads required skin data from the "Casc File": https://github.com/saintofidiocy/SCR-Graphics/blob/0e73040f7343489486cdfdabad56a67e0e870ec9/main.c#L548.

**Comment by TheNitesWhoSay** [comment]
It might be inadvisable to chase after Carbot prior to chasing after Remastered graphics (graphics & animation is btw, the bulk of what I'll be working on in the coming months).

Assuming minimal changes to the current code tips for implementation would be something like...
    - under the main menu there'd need to be something like view -> StarCraft Skin -> {Classic, Remastered, Carbot}, which would adjust a value in the current maps graphics
    - if there's any different rendering logic for terrain or sprites based on carbot selection (and I assume units->flingies are the same in the unit->flingy->sprite->grp chain) then it can call a different draw terrain/draw units/draw sprites method
    - any dat files you need to load would probably be loaded in some function off of Sc::Data::Load <https://github.com/TheNitesWhoSay/Chkdraft/blob/master/MappingCoreLib/Sc.cpp#L4319>
    - Sc::Data::Load has the opened starcraft resources - the MPQ or CASC files in "ordered source files", Sc::Data::GetAsset is then used in various places to get the dat file you need
    - more particularly you'd probably need to load whatever you needed as part of...
        - Sc::Sprite::load <https://github.com/TheNitesWhoSay/Chkdraft/blob/master/MappingCoreLib/Sc.cpp#L2371> - sprites
        - Sc::Terrain::load <https://github.com/TheNitesWhoSay/Chkdraft/blob/master/MappingCoreLib/Sc.cpp#L1976> - terrain
        - Sc::Terrain::Tiles::load <https://github.com/TheNitesWhoSay/Chkdraft/blob/master/MappingCoreLib/Sc.cpp#L1803> - singular tilesets terrain

**Comment by TheNitesWhoSay** [comment]
Remastered skins (including carbot) was finished as part of [Release 1.06](https://github.com/TheNitesWhoSay/Chkdraft/releases/tag/1.06) / https://github.com/TheNitesWhoSay/Chkdraft/pull/187
