### ISSUE TITLE
[BUG] UI bug: Toolbar not showing correct layer info

### ISSUE THREAD

**Issue by Chromowolf** [TheNitesWhoSay/Chkdraft#190]
When I'm in "Unit" layer, the upper tool bar is showing the settings of the "Terrain" layer:
![image](https://github.com/user-attachments/assets/b0dfea94-af3e-4f6d-ba44-036172018baf)

How to reproduce this bug:
Create a new map, place a unit of any type:
![image](https://github.com/user-attachments/assets/c6c66165-92fe-4fcc-b783-522393f1280f)

Close the current map, but don't close chkd:
![image](https://github.com/user-attachments/assets/d32400e2-1697-41f9-96fe-0d35e99144c7)

Create a new map again, now the side bar should auto-expanded, and can directly click a unit:
![image](https://github.com/user-attachments/assets/cc84c55c-deba-4722-9189-a3d17b8801be)

Try to place any unit, but the upper toolbar is showing "isometrical", which is not the correct layer. See above screenshot

**Comment by TheNitesWhoSay** [comment]
This should be fixed in [release 1.07](https://github.com/TheNitesWhoSay/Chkdraft/releases/tag/1.07)
