### ISSUE TITLE
Use FILENAME_MAX over MAX_PATH

### ISSUE THREAD

**Issue by RElesgoe** [TheNitesWhoSay/Chkdraft#74]
- `FILENAME_MAX` is a standard macro defined as
  
  > size needed for an array of char to hold the longest supported file name 
- `MAX_PATH` is non-standard.
- Do not use `FILENAME_MAX` when allocating memory on the stack.

**Comment by TheNitesWhoSay** [comment]
At this point, MAX_PATH is only used when calling windows functions, which I view as entirely appropriate use. When calling C++ standard-library functions FILENAME_MAX is used.
